### PR TITLE
Adding more concrete ideas to the CLDF for wordlists

### PR DESCRIPTION
**Pull request by LinguList**
This is of course open for discussion, but it summarizes the ideas I presented in the talk on the mini-workshop.

### CODE REVIEW

**Comment by xrotwang** [comment]
I'm leaning towards identifying a CLDF as wordlist via metadata. Thus, a certain setting in the metadata file (or the researcher knowing something is a wordlist) will guide the interpretation of the standard [CLDF data file](https://github.com/glottobank/cldf#the-data-file) columns. So even for wordlists, I'd stick with the column names `Parameter_ID` for the concept and `Value` for the word form.

**Comment by LinguList** [comment]
I see the point, however, given the multiple possible values we have for word forms, what is the one we take as target? The default would be the "form-in-source" I guess, that is, the typical thing we find somewhere, whichis orthography, phonetic transcription, or phonological transcription. 

And another question that is not clear to me right now: glottocode is fine to add for most languages in word lists, but often, we may also find dialects which have no glottocode yet, and our starting point is usually  to work via the language names (as we also do in LingPy), that is: local identifiers are more frequently to be expected than glottocodes, which are something like the bonus (or, say, something we should struggle to provide but cannot always provide). Would this mean, that I'd need to start from local identifiers, adding glotto-code as an extra column or in the meta-data? Similar problems will also apply to the Feature_id, since concepticon-mappings may well be missing, or link to N.A.

As an example, consider the attached file, where we have three glottocodes but 8 or 9 language varieties. 
[Bai-110-09.xlsx](https://github.com/glottobank/cldf/files/325170/Bai-110-09.xlsx)

Also available here (with more examples): https://github.com/glottobank/cognate-detection-benchmark/tree/master/datasets

I guess, for me, it would be generally helpful to start from some of these examples and to see especially how the things could be handled in concrete via meta-data and the csv-format (how do I define a language_id as local, how should I say a dataset is a wordlist, how can I annotate in human-readable form the content of a column).

**Comment by xrotwang** [comment]
Regarding the `Value` column: I think this should be the "measurement" or "coding" of a given parameter or feature in such a way that it is comparable across the dataset. I.e. if the parameter is "counterpart for meaning x" and the dataset contains words from different sources using different transcriptions, then `Value` would have to be a derived form in a common transcription across datasets.
In general my point of view is that I want to maximise the usage that can be supported given the core (Language, Parameter, Value) triples.

Regarding `Language_ID` and `Parameter_ID` I think again, the most important issue is having consistent and homogeneous values in all cells. Thus, when a dataset is meant for sharing, I'd argue it is somewhat useless if not all rows have proper glottocodes and concept set IDs.

But I think we must distinguish between the use cases "analysis" and "data curation". So in your example, I'd say start with local language identifiers in `Language_ID` and `Parameter_ID`, and whatever you think appropriate in `Value`. At this point, you don't need to add much metadata, because no amount of metadata will make it possible to make much sense of the data in a fully automated way - right? So at this stage, the processing tools will have to have knowledge about the data from other sources - possibly human input.

Once you have data that makes sense sharing, I would require commonly understood identifiers. And if this means you have to split your dataset into two - sorting our the rows which cannot be mapped - so be it. Annotating a column as - say - a glottocode is easy in the Linked Data framework, because we just need a URL for the concept "glottocode" (which we should probably provide as part of CLDF, e.g. http://cldf.clld.org/terms/glottocode) which can then be used as the value for a [propertyUrl](https://www.w3.org/TR/tabular-metadata/#cell-propertyUrl).

**Comment by LinguList** [comment]
I guess I'm fine with almost all of your points, and thanks for clarification. The only thing is this one:

> Thus, when a dataset is meant for sharing, I'd argue it is somewhat useless if not all rows have proper glottocodes and concept set IDs.

I'd say that this may slightly vary in terms of word list data:

* in many regions, like SEA, but probably also other cases, glottocode is not yet available in the fine-grained degree we want to have, as also shown in the case of the Bai dialect data
* the same applies to concepticon cases
* we know that both glotto-code and concepticon can evolve to capture things in the future, but how should we deal with it in the moment when preparing our data? I'd say, all Bai varieties have their right of being represented and shared, even if they still do not have proper glottocodes, and essentially, if I only select three and assign them a glotto-code, this will not be sharable data, since glottocode is more corse at the moment there and one would loose the essential information

For that reason, I started linking my data to glottocode now, but often, I have many varieties for the same code. 

With things like Lexibank in mind, I think that this situation may occur quite often, also if we want to allow all people to submit their data (including dialectologists, etc.), and here, the situation is different compared to typologists, who often use glottolog to identify which languages they need to code cross-linguistically, while lexical data is often the result of individual collections of people collecting word lists in some region of their interest, never having the idea of ever reaching full-world-coverage in mind. So my question would be: is there any "preferred" way to handle cases where I have my local identifiers and only partial mapping to glottocode? Maybe by adding some information that we are dealing with one variety of a glottocode?

**Comment by LinguList** [comment]
BTW: the same applies to the concepticon. One could even see such a contribution as a potential suggestion to glotto-coders and concepticons to consider updating missing values in future editions.

**Comment by xrotwang** [comment]
I fully agree that incompletely mapped data may still be useful for some and worth being shared. I just wanted to point out that this kind of data is typically not suitable for fully automated processing, thus shouldn't be fed into fully automated pipelines assuming CLDF input data. Anyway, figuring out whether any field contains glottocodes could be done completely independent of the column name, purely metadata driven, by checking whether any column specifies `http://cldf.clld.org/terms/glottocode` as `propertyUrl`.

So what to put into `Language_ID` must then be determined depending on the downstream use cases (e.g. if Edictor should remain metadata-agnostic, put into `Language_ID` whatever Edictor expects), but using a tool like `pycldf` it should be easy to re-arrange data, e.g. re-labelling columns.

**Comment by xrotwang** [comment]
So in the lexibank context I'd say the data repository can accommodate all kinds of incompletely mapped data, but the web app will only import fully mapped datasets (or the mapped subsets).

**Comment by LinguList** [comment]
Okay, sorry for being annoying, but in the lexibank context, if we have cases like in my Bai-example, where three languages are mapped to glottolog, but the data shows clearly that we have 8 varieties for these three glotto-codes: would the 8 varieties be merged into three, or completely excluded, or one randomly chosen? I still think it would make more sense, to keep these cases and also show them in the web-app, but distinguish them by the name in the source or some other attribute. Especially also when keeping in mind that we want to offer the service for people presenting there data to ease replication of experiments. If we then break it down in the web-app, this would somehow seem strange for me, and I'd be more inclined to opt for no-glotto-code tags and concepticon NA classes also shown in the web, but just showing that the linking of certain resources is lacking (as will also indicate our cldf-reports).

**Comment by xrotwang** [comment]
For me, "the data shows clearly that we have 8 varieties" means you should really get glottocodes for all the 8 varieties (which will hopefully be feasible and easy later this year). I think data aggregation (including added services on top of the aggregation) like it is done with the lexibank web app, is really difficult, if core attributes like "language" cannot be expected to behave the same. E.g. non-glottolog languoids would not be associated with a language family, or maybe they would, but just after looking up the umbrella-glottocode, could we rely on local names being globally unique? If not, how do we make them so?

For me the solution to problems caused by missing global identifier is not a big pile of heuristic workarounds but making assigning global identifiers easy :)

**Comment by LinguList** [comment]
Allright, I see this point. This would mean, that the lexibank workflow might eventually create new PRs for both Concepticon and Glottolog, if people provide new datasets, and both Glottolog and Concepticon should try and provide easy ways to deal with that.

**Comment by LinguList** [comment]
Are you okay with merging the current version as a basis for discussion, or should I put it in another file that indicates this more directly, that it is a statement on current practice in tools rather than a fixed format?

**Comment by xrotwang** [comment]
Go ahead and merge!
Am 21.06.2016 13:52 schrieb "Johann-Mattis List" <notifications@github.com>:

**Comment by d97hah** [comment]
Sorry to join in the conversation a little late. I agree/opine that:
1. There will always be varieties one wants to put in CLDF files that
glottolog does not aim to have codes for, for example if a CLDF records
idiolects in some experiment or the like. In such cases it seems nothing
prevents there being an application-specific ID (which, say, defaults to
the glottocode if none given).
2. It is likely that cases like Mattis' provoke a relatively speedy set of
changes to the inventory of Glottolog

2016-06-21 13:43 GMT+02:00 Johann-Mattis List <notifications@github.com>:

**Pull request merged**
